name: logpot
description: ""
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  intl: ^0.20.2
  logging: ^1.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0

executables:
  logpot: bin/logpot.dart
