name: logpot
description: "Webserver logging incoming request and displaying it for analytical purposes"
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.6.0
  intl: ^0.20.2
  logging: ^1.3.0
  shelf: ^1.4.0
  shelf_limiter: ^2.0.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  logpot: bin/logpot.dart
